apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-pvc
  labels:
    app: hello-world
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi